name: challenges
version: 0.1.0.0
github: "aleksimart/challenges"
license: BSD3
author: "Aleksei"
maintainer: "alekmartir@gmail.com"
copyright: "AlAl"

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/aleksimart/challenges#readme>

dependencies:
  - base >= 4.7 && < 5
  - random
  - deepseq

library:
  source-dirs: src

executables:
  challenges-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - challenges

tests:
  challenges-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - challenges
